PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?s ?o WHERE { 
	?s  rdfs:subClassOf  ?o .
	?s a owl:Class .
	FILTER (isBlank(?o))
	FILTER (!isBlank(?s))
}