PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?class ?subclass WHERE {
	?subclass rdfs:subClassOf+ ?class .
	FILTER(?class NOT IN (owl:Thing))
	FILTER(!isBlank(?class))
	FILTER(!isBlank(?subclass))
}